#include "graphics/camera.h"

#include <cmath>

#include <glm/gtc/matrix_transform.hpp>

namespace voxels::graphics {

    Camera::Camera(float fov, float aspect_ratio, float near_plane, float far_plane)
        : fov_(fov),
        aspect_ratio_(aspect_ratio),
        near_plane_(near_plane),
        far_plane_(far_plane),
        position_(0.0f, 100.0f, 0.0f),
        pitch_(0.0f),
        yaw_(0.0f)
    {}

    glm::mat4 Camera::GetViewMatrix() const noexcept {
        glm::vec3 forward;
        forward.x = cos(pitch_) * cos(yaw_);
        forward.y = sin(pitch_);
        forward.z = cos(pitch_) * sin(yaw_);
        forward = glm::normalize(forward);

        return glm::lookAt(position_, position_ + forward, glm::vec3(0.0f, 1.0f, 0.0f));
    }

    glm::mat4 Camera::GetProjectionMatrix() const noexcept {
        return glm::perspective(fov_, aspect_ratio_, near_plane_, far_plane_);
    }

    util::Frustum Camera::GetFrustum(const glm::mat4& view_proj_mat) const noexcept {
        util::Frustum frustum;

        // Generated by Gemini
        // Left Plane (w + x)
        frustum.planes[0].normal.x = view_proj_mat[0][3] + view_proj_mat[0][0];
        frustum.planes[0].normal.y = view_proj_mat[1][3] + view_proj_mat[1][0];
        frustum.planes[0].normal.z = view_proj_mat[2][3] + view_proj_mat[2][0];
        frustum.planes[0].distance = view_proj_mat[3][3] + view_proj_mat[3][0];

        // Right Plane (w - x)
        frustum.planes[1].normal.x = view_proj_mat[0][3] - view_proj_mat[0][0];
        frustum.planes[1].normal.y = view_proj_mat[1][3] - view_proj_mat[1][0];
        frustum.planes[1].normal.z = view_proj_mat[2][3] - view_proj_mat[2][0];
        frustum.planes[1].distance = view_proj_mat[3][3] - view_proj_mat[3][0];

        // Bottom Plane (w + y)
        frustum.planes[2].normal.x = view_proj_mat[0][3] + view_proj_mat[0][1];
        frustum.planes[2].normal.y = view_proj_mat[1][3] + view_proj_mat[1][1];
        frustum.planes[2].normal.z = view_proj_mat[2][3] + view_proj_mat[2][1];
        frustum.planes[2].distance = view_proj_mat[3][3] + view_proj_mat[3][1];

        // Top Plane (w - y)
        frustum.planes[3].normal.x = view_proj_mat[0][3] - view_proj_mat[0][1];
        frustum.planes[3].normal.y = view_proj_mat[1][3] - view_proj_mat[1][1];
        frustum.planes[3].normal.z = view_proj_mat[2][3] - view_proj_mat[2][1];
        frustum.planes[3].distance = view_proj_mat[3][3] - view_proj_mat[3][1];

        // Near Plane (w + z) - OpenGL standard (-1 to 1)
        frustum.planes[4].normal.x = view_proj_mat[0][3] + view_proj_mat[0][2];
        frustum.planes[4].normal.y = view_proj_mat[1][3] + view_proj_mat[1][2];
        frustum.planes[4].normal.z = view_proj_mat[2][3] + view_proj_mat[2][2];
        frustum.planes[4].distance = view_proj_mat[3][3] + view_proj_mat[3][2];

        // Far Plane (w - z)
        frustum.planes[5].normal.x = view_proj_mat[0][3] - view_proj_mat[0][2];
        frustum.planes[5].normal.y = view_proj_mat[1][3] - view_proj_mat[1][2];
        frustum.planes[5].normal.z = view_proj_mat[2][3] - view_proj_mat[2][2];
        frustum.planes[5].distance = view_proj_mat[3][3] - view_proj_mat[3][2];

        frustum.NormalizePlanes();
        return frustum;
    }

    util::Frustum Camera::GetFrustum() const noexcept {
        return GetFrustum(GetViewProjectionMatrix());
    }

}
